@echo off
echo Rodando script TestaPilha...
TRAB3-2.exe /sTestaPilha.script >SaidaPilha.log
echo Abrindo os resultados...
start notepad "SaidaPilha.log"
echo Rodando script TestaReconhecedorLexico...
TRAB3-1.exe /sTestaReconhecedorLexico.script >SaidaReconhecedorLexico.log
echo Abrindo os resultados...
start notepad "SaidaReconhecedorLexico.log"
echo Rodando script TestaExemplosAutomatosFinitos...
TRAB3-1.exe /sTestaExemplosAutomatosFinitos.script >SaidaAutomatosFinitos.log
echo Abrindo os resultados...
start notepad "SaidaAutomatosFinitos.log"