@echo off
echo Rodando script TestaVertice...
TRAB3-4.exe /sTestaVertice.script >SaidaVertice.log
echo Abrindo os resultados...
start notepad "SaidaVertice.log"

echo Rodando script TestaGrafo...
TRAB3-3.exe /sTestaGrafo.script >SaidaGrafo.log
echo Abrindo os resultados...
start notepad "SaidaGrafo.log"

echo Rodando script TestaPilha...
TRAB3-2.exe /sTestaPilha.script >SaidaPilha.log
echo Abrindo os resultados...
start notepad "SaidaPilha.log"

echo Rodando script TestaReconhecedorLexico...
TRAB3-1.exe /sTestaReconhecedorLexico.script >SaidaReconhecedorLexico.log
echo Abrindo os resultados...
start notepad "SaidaReconhecedorLexico.log"