#if ! defined( ALEX_ )
#define ALEX_
/***************************************************************************
*
*  $MCD Módulo de implementação: ALX Analizador Léxico
*
*  Arquivo gerado:              ALEX.h
*  Letras identificadoras:      ALX
*
*  Curso: INF 1301 Programação Modular
*  Orientador: Flavio Bevilacqua
*  Autores:   gui   Guilherme Dantas
*             cai   Caique Molina
*             nag   Nagib Suaid
*
*  $HA Histórico de evolução:
*     Versão  Autor    Data     Observações
*     1       gui   17/09/2018  início do desenvolvimento
*
*  $ED Descrição do módulo
*     
*     WIP
*
***************************************************************************/

#if defined( ALEX_OWN )
   #define ALEX_EXT
#else
   #define ALEX_EXT extern
#endif

#include "ALEX.H"

/***** Declarações exportadas pelo módulo *****/

#undef ALEX_EXT

/********** Fim do módulo de definição: GRF  Grafo **********/

#else
#endif
