#if ! defined( ARESTA_ )
#define ARESTA_
/***************************************************************************
*
*  $MCD Módulo de implementação: ARE  Aresta
*
*  Arquivo gerado:              ARESTA.h
*  Letras identificadoras:      ARE
*
*  Curso: INF 1301 Programação Modular
*  Orientador: Flavio Bevilacqua
*  Autores:   gui   Guilherme Dantas
*             cai   Caique Molina
*             nag   Nagib Suaid
*
*  $HA Histórico de evolução:
*     Versão  Autor    Data     Observações
*     1       gui   17/09/2018  início do desenvolvimento
*
*  $ED Descrição do módulo
*     
*     WIP
*
***************************************************************************/

#if defined( ARESTA_OWN )
   #define ARESTA_EXT
#else
   #define ARESTA_EXT extern
#endif

/***** Declarações exportadas pelo módulo *****/

/* Tipo referência para uma aresta */

#undef ARESTA_EXT

/********** Fim do módulo de definição: ARE  Aresta **********/

#else
#endif
